[package]
name = "pixo2ecas"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.polars]
version = "0.21.0"
features = ["lazy", "strings"]

[dependencies]
polars-lazy = "0.21.0"
polars-core = "0.21.0"
